repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-case-conflict
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: double-quote-string-fixer
    -   id: check-yaml
-   repo: git@github.com:asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
    -   id: reorder-python-imports
