name: sl-scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Cache vdb
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/vdb
        key: ${{ runner.os }}
    - name: Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        VDB_HOME: ${{ github.workspace }}/vdb
        WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
        SCAN_AUTO_BUILD: true
        SCAN_ANNOTATE_PR: true
        PR_COMMENT_TEMPLATE: "## Scan Summary\n%(summary)s\n## Recommendation\n%(recommendation)s\n"
        PR_COMMENT_BASIC_TEMPLATE: "## Scan Summary\n%(summary)s\n## Recommendation\n%(recommendation)s\n"
      with:
        output: reports
        type: "credscan, python, dockerfile, yaml"
    - name: Upload scan reports
      uses: actions/upload-artifact@v3.0.0
      with:
        name: shiftleft-scan-reports
        path: reports